// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MarketplaceLoadErrorInfo } from "./MarketplaceLoadErrorInfo";
import type { PluginMarketplaceEntry } from "./PluginMarketplaceEntry";

export type PluginListResponse = { marketplaces: Array<PluginMarketplaceEntry>,
/**
 * Marketplace files that failed to load. These entries are omitted from
 * `marketplaces` so clients can fail open while still surfacing the issue.
 */
marketplaceLoadErrors: Array<MarketplaceLoadErrorInfo>, remoteSyncError: string | null, featuredPluginIds: Array<string>, };
