// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMode } from "../AuthMode";
import type { PlanType } from "../PlanType";

export type SavedAccount = { id: string, isCurrent: boolean, authMode: AuthMode, email: string | null, workspaceId: string | null, planType: PlanType | null, apiKeySuffix: string | null, };
